#!/bin/csh -f
set andrewdir = `andrewdirs andrewdir`

set rnessrun = nessrun
set conv_n = ${andrewdir}lib/c++conv/c2c++.n

if ( ${#argv} == 0 ) then
	echo "usage: C++Conv files ... --- classindex"
	exit 1
endif

exec $rnessrun $conv_n $argv:q
