#!/bin/csh -f

if ( ${#argv} == 0 ) then
	echo 'usage: C++Index directories... [--- -Idir1 -Idir2 etc... ]'
	exit 1
endif

set flag = 0

set includes=()
set dirs=()
while   (${#argv} > 0)
	if ("$argv[1]:q" == "---") then
		set flag = 1
		shift
	endif
	if ("$flag" == "0") then
		set dirs=($dirs:q $argv[1]:q)
	else 
		set includes=($includes:q $argv[1]:q)
	endif
	shift	
end

find $dirs -name '*.ch' -print | classindex $includes

