#!/bin/csh -efx
rm -rf tmpdir tmpdir2
mkdir tmpdir tmpdir2
cd tmpdir
set list=()
set haveversion=0
set arglist=(`echo $argv:q|tr ' ' '\012'|sort -u`)
foreach lib ($arglist)
	set tail=$lib:t
	if ("$tail" != "libafs.a") then
	set objname=`echo $lib|sed -e s@/@_@g`
	set list=($list ../tmpdir2/$objname.o)
	ar x $lib
	if $haveversion != 0 then
		rm -f AFS_component_version_number.o AFS_component_ RX_component_v
	endif
	if (-e AFS_component_ || -e AFS_component_version_number.o || -e RX_component_v) then
		set haveversion=1
	endif
#	if (-e casestrcpy.o) then
#		rm casestrcpy.o
#	endif
	ld -r -o ../tmpdir2/$objname.obj *
              rm -f * 
	endif
end
foreach lib (../tmpdir2/*.obj)
	mv $lib $lib:r.o
end
ld -r -o ../allafs.o $list
cd ..
rm -rf tmpdir tmpdir2
exit 0

