#!/bin/csh -f
set name = $1
shift
set basedir = $1
shift
set linkprefix = "$1"
shift
onintr error
echo "making lib"$name.so
rm -f lib$name.so
echo "Creating shared object."
$linkprefix gcc -shared -o lib$name.so $argv:q
if ($status != 0) then
	echo Could not create shared library: lib$name.so.
	rm ,lib$name.so
	exit 1
endif
exit 0
error:
	rm -f lib$name.so ,lib$name.so
exit 1
