\begindata{text,539653208}
\textdsversion{12}
\template{default}


\begindata{link,539654104}
Datastream version: 3
$ANDREWDIR/doc/PROGRAMMER/atomlist.doc
0
0
\begindata{link,539654104}
Datastream version: 2
atomlist
2

black
white
\enddata{link,539654104}
\enddata{link,539654104}
\view{linkview,539654104,9,0,0}atomlist.doc - list of atoms


\begindata{link,539654536}
Datastream version: 3
$ANDREWDIR/doc/PROGRAMMER/dataobj.doc
0
0
\begindata{link,539654536}
Datastream version: 2
dataobj
2

black
white
\enddata{link,539654536}
\enddata{link,539654536}
\view{linkview,539654536,10,0,0}dataobj.doc - provides the data and methods 
needed to maintain, store and manipulate information


\begindata{link,539655512}
Datastream version: 3
$ANDREWDIR/doc/PROGRAMMER/event.doc
0
0
\begindata{link,539655512}
Datastream version: 2
event
2

black
white
\enddata{link,539655512}
\enddata{link,539655512}
\view{linkview,539655512,12,0,0}event.doc - the Interaction Manager (im) 
uses this class to schedule events that application programs generate


\begindata{link,539655960}
Datastream version: 3
$ANDREWDIR/doc/PROGRAMMER/filetype.doc
0
0
\begindata{link,539655960}
Datastream version: 2
filetype
2

black
white
\enddata{link,539655960}
\enddata{link,539655960}
\view{linkview,539655960,13,0,0}filetype.doc - provides the class 
procedures for accessing and modifying file type information



\begindata{link,539656888}
Datastream version: 3
$ANDREWDIR/doc/PROGRAMMER/observe.doc
0
0
\begindata{link,539656888}
Datastream version: 2
observe
2

black
white
\enddata{link,539656888}
\enddata{link,539656888}
\view{linkview,539656888,15,0,0}observe.doc - provides the methods, class 
procedures and data structures needed for one object, the observed or 
observable object, to communicate about changes with another object, the 
observer


\begindata{link,539659992}
Datastream version: 3
$ANDREWDIR/doc/PROGRAMMER/region.doc
0
0
\begindata{link,539659992}
Datastream version: 2
region
2

black
white
\enddata{link,539659992}
\enddata{link,539659992}
\view{linkview,539659992,17,0,0}region.doc - quick reference list for region


\begindata{link,539660536}
Datastream version: 3
$ANDREWDIR/doc/PROGRAMMER/rm.doc
0
0
\begindata{link,539660536}
Datastream version: 2
rm
2

black
white
\enddata{link,539660536}
\enddata{link,539660536}
\view{linkview,539660536,18,0,0}rm.doc - quick reference list for the 
resource manager


\begindata{link,539660984}
Datastream version: 3
$ANDREWDIR/doc/PROGRAMMER/updlist.doc
0
0
\begindata{link,539660984}
Datastream version: 2
updlist
2

black
white
\enddata{link,539660984}
\enddata{link,539660984}
\view{linkview,539660984,19,0,0}updlist.doc - provides a mechanism for  a 
view to maintain a list of its children that have requested an update


\begindata{link,539661544}
Datastream version: 3
$ANDREWDIR/doc/PROGRAMMER/view.doc
0
0
\begindata{link,539661544}
Datastream version: 2
view
2

black
white
\enddata{link,539661544}
\enddata{link,539661544}
\view{linkview,539661544,20,0,0}view.doc - provides the methods, class 
procedures and data structures needed to (1) display information (often 
associated with a data object) in a rectangular area on the screen, (2) 
request display updates and respond to such requests, and (3) respond to 
input events generated by the user


\begindata{link,539831816}
Datastream version: 3
$ANDREWDIR/doc/PROGRAMMER/frame.doc
0
0
\begindata{link,539831816}
Datastream version: 2
frame
2

black
white
\enddata{link,539831816}
\enddata{link,539831816}
\view{linkview,539831816,22,0,0}frame.doc - a view that provides a message 
interface


\begindata{link,539833224}
Datastream version: 3
$ANDREWDIR/doc/PROGRAMMER/buffer.doc
0
0
\begindata{link,539833224}
Datastream version: 2
buffer
2

black
white
\enddata{link,539833224}
\enddata{link,539833224}
\view{linkview,539833224,25,0,0}buffer.doc - provides a set of routines to 
manage a set of views corresponding to a set of data objects


\begindata{link,539834712}
Datastream version: 3
$ANDREWDIR/doc/PROGRAMMER/rectlist.doc
0
0
\begindata{link,539834712}
Datastream version: 2
rectlist
2

black
white
\enddata{link,539834712}
\enddata{link,539834712}
\view{linkview,539834712,28,0,0}rectlist.doc - provides class procedures 
for creating and modifying rectangle lists


\begindata{link,539835192}
Datastream version: 3
$ANDREWDIR/doc/PROGRAMMER/style.doc
0
0
\begindata{link,539835192}
Datastream version: 2
style
2

black
white
\enddata{link,539835192}
\enddata{link,539835192}
\view{linkview,539835192,29,0,0}style.doc - collection of attributes which 
can be applied to a region of data


\begindata{link,539835688}
Datastream version: 3
$ANDREWDIR/doc/PROGRAMMER/stylesht.doc
0
0
\begindata{link,539835688}
Datastream version: 2
stylesht
2

black
white
\enddata{link,539835688}
\enddata{link,539835688}
\view{linkview,539835688,30,0,0}stylesht.doc - collection of the styles 
which have been defined for use in a particular object


\begindata{link,539836120}
Datastream version: 3
$ANDREWDIR/doc/PROGRAMMER/tree23.doc
0
0
\begindata{link,539836120}
Datastream version: 2
tree23
2

black
white
\enddata{link,539836120}
\enddata{link,539836120}
\view{linkview,539836120,31,0,0}tree23.doc - structure used to manage 
styles in the Andrew Toolkit


\begindata{link,539838616}
Datastream version: 3
$ANDREWDIR/doc/PROGRAMMER/lpair.doc
0
0
\begindata{link,539838616}
Datastream version: 2
lpair
2

black
white
\enddata{link,539838616}
\enddata{link,539838616}
\view{linkview,539838616,36,0,0}lpair.doc - provides methods and class 
procedures for placing one view above another in a rectangle (vertical 
split) or placing two views side by side in a rectangle (horizontal split)


\begindata{link,539840728}
Datastream version: 3
$ANDREWDIR/doc/PROGRAMMER/oscroll.doc
0
0
\begindata{link,539840728}
Datastream version: 2
oscroll
2

black
white
\enddata{link,539840728}
\enddata{link,539840728}
\view{linkview,539840728,40,0,0}oscroll.doc - provides methods and class 
procedures for creating scroll bars in a view


\begindata{link,539841704}
Datastream version: 3
$ANDREWDIR/doc/PROGRAMMER/scroll.doc
0
0
\begindata{link,539841704}
Datastream version: 2
scroll
2

black
white
\enddata{link,539841704}
\enddata{link,539841704}
\view{linkview,539841704,42,0,0}scroll.doc - provides methods and class 
procedures for creating scroll bars in a view


\begindata{link,539844648}
Datastream version: 3
$ANDREWDIR/doc/PROGRAMMER/header.doc
0
0
\begindata{link,539844648}
Datastream version: 2
header
2

black
white
\enddata{link,539844648}
\enddata{link,539844648}
\view{linkview,539844648,48,0,0}header.doc - provides an interface for the 
user or programmer to set the headers and footers which should be shown 
when a document is printed


\begindata{link,539845096}
Datastream version: 3
$ANDREWDIR/doc/PROGRAMMER/search.doc
0
0
\begindata{link,539845096}
Datastream version: 2
search
2

black
white
\enddata{link,539845096}
\enddata{link,539845096}
\view{linkview,539845096,49,0,0}search.doc - provides class procedures for 
searching forwards and backwards for patterns in a text document


\begindata{link,539845608}
Datastream version: 3
$ANDREWDIR/doc/PROGRAMMER/smpltext.doc
0
0
\begindata{link,539845608}
Datastream version: 2
smpltext
2

black
white
\enddata{link,539845608}
\enddata{link,539845608}
\view{linkview,539845608,50,0,0}smpltext.doc - provides simple editable text


\begindata{link,539846040}
Datastream version: 3
$ANDREWDIR/doc/PROGRAMMER/tabs.doc
0
0
\begindata{link,539846040}
Datastream version: 2
tabs
2

black
white
\enddata{link,539846040}
\enddata{link,539846040}
\view{linkview,539846040,51,0,0}tabs.doc - provides routines for handling a 
list of tabstops


\begindata{link,539846584}
Datastream version: 3
$ANDREWDIR/doc/PROGRAMMER/textv.doc
0
0
\begindata{link,539846584}
Datastream version: 2
textv
2

black
white
\enddata{link,539846584}
\enddata{link,539846584}
\view{linkview,539846584,52,0,0}textv.doc - provides the methods can class 
procedures needed to view text on a workstation screen and to edit that text


\begindata{link,539846984}
Datastream version: 3
$ANDREWDIR/doc/PROGRAMMER/txtstvec.doc
0
0
\begindata{link,539846984}
Datastream version: 2
txtstvec
2

black
white
\enddata{link,539846984}
\enddata{link,539846984}
\view{linkview,539846984,53,0,0}txtstvec.doc - holds a complete snapshot of 
text formatting


\begindata{link,539847928}
Datastream version: 3
$ANDREWDIR/doc/PROGRAMMER/panel.doc
0
0
\begindata{link,539847928}
Datastream version: 2
panel
2

black
white
\enddata{link,539847928}
\enddata{link,539847928}
\view{linkview,539847928,55,0,0}panel.doc - supports simple caption lists


\begindata{link,539848600}
Datastream version: 3
$ANDREWDIR/doc/PROGRAMMER/fontdesc.doc
0
0
\begindata{link,539848600}
Datastream version: 2
fontdesc
2

black
white
\enddata{link,539848600}
\enddata{link,539848600}
\view{linkview,539848600,56,0,0}fontdesc.doc - provides methods and class 
procedures for creating font descriptors that you need to access the Andrew 
font library


\begindata{link,539849032}
Datastream version: 3
$ANDREWDIR/doc/PROGRAMMER/graphic.doc
0
0
\begindata{link,539849032}
Datastream version: 2
graphic
2

black
white
\enddata{link,539849032}
\enddata{link,539849032}
\view{linkview,539849032,57,0,0}graphic.doc - provides methods for drawing 
lines, shapes, and text as well as methods for transferring entire blocks 
of bits


\begindata{link,539849544}
Datastream version: 3
$ANDREWDIR/doc/PROGRAMMER/im.doc
0
0
\begindata{link,539849544}
Datastream version: 2
im
2

black
white
\enddata{link,539849544}
\enddata{link,539849544}
\view{linkview,539849544,58,0,0}im.doc - handles all the "administrative" 
duties in the event-driven Andrew Toolkit system, such as determining what 
functions need to be called when and then calls those functions.  It also 
controls some aspects of window appearance.


\begindata{link,539849992}
Datastream version: 3
$ANDREWDIR/doc/PROGRAMMER/init.doc
0
0
\begindata{link,539849992}
Datastream version: 2
init
2

black
white
\enddata{link,539849992}
\enddata{link,539849992}
\view{linkview,539849992,59,0,0}init.doc - contains functions necessary for 
user customizations


\begindata{link,539850552}
Datastream version: 3
$ANDREWDIR/doc/PROGRAMMER/keymap.doc
0
0
\begindata{link,539850552}
Datastream version: 2
keymap
2

black
white
\enddata{link,539850552}
\enddata{link,539850552}
\view{linkview,539850552,60,0,0}keymap.doc - provide a set of facilities 
that allow you to bind sequences of keyboard characters to keyboard command 
procedures


\begindata{link,539850952}
Datastream version: 3
$ANDREWDIR/doc/PROGRAMMER/keystate.doc
0
0
\begindata{link,539850952}
Datastream version: 2
keystate
2

black
white
\enddata{link,539850952}
\enddata{link,539850952}
\view{linkview,539850952,61,0,0}keystate.doc - quick reference list for 
keystate (see keymaps documentation)


\begindata{link,539851464}
Datastream version: 3
$ANDREWDIR/doc/PROGRAMMER/menulist.doc
0
0
\begindata{link,539851464}
Datastream version: 2
menulist
2

black
white
\enddata{link,539851464}
\enddata{link,539851464}
\view{linkview,539851464,62,0,0}menulist.doc - provides stacks of menu 
cards that a user can pop-up within the body of your program's windows


\begindata{link,539851896}
Datastream version: 3
$ANDREWDIR/doc/PROGRAMMER/message.doc
0
0
\begindata{link,539851896}
Datastream version: 2
message
2

black
white
\enddata{link,539851896}
\enddata{link,539851896}
\view{linkview,539851896,63,0,0}message.doc - interface for displaying 
information to the user and asking the user questions


\begindata{link,539852936}
Datastream version: 3
$ANDREWDIR/doc/PROGRAMMER/proctbl.doc
0
0
\begindata{link,539852936}
Datastream version: 2
proctbl
2

black
white
\enddata{link,539852936}
\enddata{link,539852936}
\view{linkview,539852936,65,0,0}proctbl.doc - a global table containing all 
of the commands bound to either keys or menu items in the system


\begindata{link,539853432}
Datastream version: 3
$ANDREWDIR/doc/PROGRAMMER/envrment.doc
0
0
\begindata{link,539853432}
Datastream version: 2
envrment
2

black
white
\enddata{link,539853432}
\enddata{link,539853432}
\view{linkview,539853432,66,0,0}envrment.doc - provides the methods and 
class procedures for wrapping a text region in an environment


Note: some doc links formerly here have been removed due to being 
nothing more than stub documents.
\enddata{text,539653208}
