#!/bin/csh -f
set name = $1
shift
set basedir = $1
shift
set linkprefix = "$1"
shift
echo "making lib"$name.so
rm -f lib$name.so.1.0
set list = ()
foreach ename ($argv:q)
	echo -n --$ename-- 
	if ("$ename:e" == "o" || "$ename:e" == "a") then 
		set list = ($list $ename)
	endif
end
echo
echo "Creating shared object."
$linkprefix ld  -dp -dc -Bshareable -o lib$name.so.1.0 $list $basedir/lib/dynlink/init.o
if ($status != 0) then
	echo Could not create shared library: lib$name.so.1.0
	exit -1
endif
exit 0
