boolean rasterview_FindFrameHelp(class frame  *frame, class im  *im);
void rasterview_CurrentDirectory(class rasterview  *self, char  *f);
void rasterview_CenterViewSelection(class rasterview  *self);
void rasterview_ViewHideHighlight(class rasterview  *self);
void rasterview_CorrectHighlight(class rasterview  *self);
void rasterview_DrawPanHighlight(class rasterview  *self, short  g);
void rasterview_ZoomToVisualBounds(class rasterview  *self, long  x , long  y);
void rasterview_UpdateZoomedSelection(class rasterview  *self, long  x , long  y);
void rasterview_ToggleCoordProc(class rasterview  *self, char  *rock);
void rasterview_MakeToolsetProc(class rasterview  *self, char  *rock);
void rasterview_KillToolsetProc(class rasterview  *self, char  *rock);
void rasterview_OverlayInsetProc(class rasterview  *self, const char  *rock);
void rasterview_RemoveInsetProc(class rasterview  *self, char  *rock);
void rasterview_ResizeInsetProc(class rasterview  *self, char  *rock);
void rasterview_ImprintInsetProc(class rasterview  *self, long  rock);
void rasterview_CenterCommand(class rasterview  *self, long  rock);
void rasterview_ZoomInCommand(class rasterview  *self, long  rock);
void rasterview_ReflectChangesInExpansion(class rasterview  *self, struct rectangle  *R);
void rasterview_MoveDisplayBoxCommand(class rasterview  *self, long  rock);
void rasterview_FinishMovingDisplayBox(class rasterview  *self, long  x , long  y);
void rasterview_ZoomOutCommand(class rasterview  *self, long  rock);
void rasterview_RegionSelectCommand(class rasterview  *self, long  rock);
void TouchUpCommand(class rasterview  *self, long  rock);
void PanCommand(class rasterview  *self, long  rock);
void ToolCommand(class rasterview  *self, long  rock);
void rasterview_RotateCommand(class rasterview  *self, long  rock);
void ReadRaster(class rasterview  *self, class raster  *ras, char  *filename);
void WriteFileCommand(class rasterview  *self );
boolean MatExtendPossible(class rasterview  *self);
void rasterview_RealPostMenus(class rasterview  *self);
