extern NO_DLL_EXPORT boolean rasterview_FindFrameHelp(class frame  *frame, class im  *im);
extern NO_DLL_EXPORT void rasterview_CurrentDirectory(class rasterview  *self, char  *f);
extern NO_DLL_EXPORT void rasterview_CenterViewSelection(class rasterview  *self);
extern NO_DLL_EXPORT void rasterview_ViewHideHighlight(class rasterview  *self);
extern NO_DLL_EXPORT void rasterview_CorrectHighlight(class rasterview  *self);
extern NO_DLL_EXPORT void rasterview_DrawPanHighlight(class rasterview  *self, short  g);
extern NO_DLL_EXPORT void rasterview_ZoomToVisualBounds(class rasterview  *self, long  x , long  y);
extern NO_DLL_EXPORT void rasterview_UpdateZoomedSelection(class rasterview  *self, long  x , long  y);
extern NO_DLL_EXPORT void rasterview_ToggleCoordProc(class rasterview  *self, char  *rock);
extern NO_DLL_EXPORT void rasterview_MakeToolsetProc(class rasterview  *self, char  *rock);
extern NO_DLL_EXPORT void rasterview_KillToolsetProc(class rasterview  *self, char  *rock);
extern NO_DLL_EXPORT void rasterview_OverlayInsetProc(class rasterview  *self, const char  *rock);
extern NO_DLL_EXPORT void rasterview_RemoveInsetProc(class rasterview  *self, char  *rock);
extern NO_DLL_EXPORT void rasterview_ResizeInsetProc(class rasterview  *self, char  *rock);
extern NO_DLL_EXPORT void rasterview_ImprintInsetProc(class rasterview  *self, long  rock);
extern NO_DLL_EXPORT void rasterview_CenterCommand(class rasterview  *self, long  rock);
extern NO_DLL_EXPORT void rasterview_ZoomInCommand(class rasterview  *self, long  rock);
extern NO_DLL_EXPORT void rasterview_ReflectChangesInExpansion(class rasterview  *self, struct rectangle  *R);
extern NO_DLL_EXPORT void rasterview_MoveDisplayBoxCommand(class rasterview  *self, long  rock);
extern NO_DLL_EXPORT void rasterview_FinishMovingDisplayBox(class rasterview  *self, long  x , long  y);
extern NO_DLL_EXPORT void rasterview_ZoomOutCommand(class rasterview  *self, long  rock);
extern NO_DLL_EXPORT void rasterview_RegionSelectCommand(class rasterview  *self, long  rock);
extern NO_DLL_EXPORT void TouchUpCommand(class rasterview  *self, long  rock);
extern NO_DLL_EXPORT void PanCommand(class rasterview  *self, long  rock);
extern NO_DLL_EXPORT void ToolCommand(class rasterview  *self, long  rock);
extern NO_DLL_EXPORT void rasterview_RotateCommand(class rasterview  *self, long  rock);
extern NO_DLL_EXPORT void ReadRaster(class rasterview  *self, class raster  *ras, char  *filename);
extern NO_DLL_EXPORT void WriteFileCommand(class rasterview  *self );
extern NO_DLL_EXPORT boolean MatExtendPossible(class rasterview  *self);
extern NO_DLL_EXPORT void rasterview_RealPostMenus(class rasterview  *self);
