#!/bin/sh
#
# USAGE:  installapp app destdir
cmdpath="$2/$1.cmd"

rm -f $cmdpath
cat > $cmdpath <<!
/*REXX start up $1*/
parse arg arguments

'@ECHO OFF'
'runapp $1app ' arguments
exit
!
exit 0


