#!/bin/sh
# USAGE:  installdll dllname destdir
#
# Expands/truncates dllname into a-dllname in 8 chars and installs
shortname="`echo $1 | cut -c1-6`"
dllname="a-$shortname" # make it unique for ATK.
set -x
install -m 555 $dllname.dll $2


