#include <view.H>
extern void spread_ScrollLogically(class spread *V,long tr, long lc, long br, long rc, struct rectangle *logical);
extern void IgnoreObserved(class table  *T);
extern void RemoveCellView(class table  *T,struct cell  *c,class view  *v);
extern void DestroyCell(class table  *T, struct cell  *oldcell);
extern void rangeLimit (class table  * T, Chunk  chunk);
extern void rcref (class table  * T, extended_double  *result, int      r , int      c , int      iftaped);
extern void MakeStandard(extended_double  *x, double  value);
extern void MakeBogus(extended_double  *x, const char  *message);
extern int isrange (extended_double  *x);
extern int     idate (int      y, int      m, int      d);
extern void enterfuns (void);
 
extern void  eval (class table  * T, extended_double  *result, int      r , int      c, const char    *input);
void enterfun (const char      *name, double  (*fptr)(), int      argc);
extern void syntaxError ();
extern class view * spread_FindSubview (class spread  * V, struct cell  * cell);
extern void ComputeRowSizes(class spread  *V);
extern long spread_Width(class spread  * V, int  i, int  j);
extern long spread_Height(class spread  * V, int  i, int  j);
extern int spread_WantHighlight(class spread  *V);
extern void spread_update_FullUpdate(class spread  * V, enum view_UpdateType  how, struct rectangle  *updateClipRect);
extern void spread_PartialUpdate(class spread  * V, enum view_UpdateType  how, struct rectangle  *updateClipRect);
extern void spread_InvertRectangle(class spread  * V, int  left , int  top , int  width , int  height);
extern void spread_ClearSelectionBox (class spread  * V );
extern void k_SetMessageState (class spread  * V, int  newstate);
extern void CopyChunk(Chunk  to, Chunk  from);
extern boolean CompareChunk(Chunk  to, Chunk  from);
extern void SetCurrentCell (class spread  * V, Chunk  chunk, boolean expose=TRUE);
extern void TellFormula (class spread  * V);
extern void GetFormula (class spread  * V, Chunk  chunk, char  **keybuff);
extern void k_TellUser (class spread  * V, const char    *s);
extern boolean k_AskUser (class spread  * V, const char  prompt[], const char  def[], char  buff[], int  n);
extern boolean k_AreYouSure (class spread  * V, const char  *why);
extern boolean k_WantToDiscard (class spread  * V);
extern void WriteTroff(class spread  * V, FILE  * f, const char  *processor, const char  *format, boolean toplevel);
extern void AddRows(class spread  * V, int  after , int  count);
extern void AddCols(class spread  * V, int  after , int  count);
extern void k_DefineKeys (class keymap  *mainmap, class keymap *readonlymap, struct ATKregistryEntry   *classinfo);
extern void DefineMenus (class menulist  *mainmenus, class keymap  * mainmap, class menulist *readonlymenus, class keymap *readonlymap, struct ATKregistryEntry   *classinfo);
extern void ResetCurrentCell (class spread  * V);
extern class view * MouseHit (class spread  * V, enum view_MouseAction  action, long  x , long  y, long  numberOfClicks		/* how should i use this?? */);
extern void WriteASCII (class table  * T, FILE  *f, Chunk  chunk, int  level);
extern class table * ReadASCII (class table  * T, FILE  *f);
extern void WriteCell (class table  * T, FILE  *f, struct cell  * cell, char  **buff, int  level);
extern void ReadCell(class table  *T, FILE  *f, char  *buff, char  **cpp, char  *cl, struct cell  *cell);
extern void spread_ClearSelectionBox (class spread  * V );
extern void InitializeGraphic(class spread  *V);

