######################################################################
# File Exchange include/ Makefile
#
# Copyright 1990 by the Massachusetts Institute of Technology.
#
# For copying and distribution information, please see the file
# <mit-copyright.h>.
######################################################################

all: fxcl.h fxserver.h fx-internal.h memory.h

install:
	@echo "(No action taken to install header files.)"

clean:
	-rm -f *~ *_err.h fx_prot.h
