#!/bin/csh -f
set name = $1
shift
set basedir = $1
shift
set linkprefix = "$1"
shift
echo "making lib"$name.sl
rm -f lib$name.sl
echo "Creating shared object."
$linkprefix CC -Wl,+s,+b,:,-E -b -o lib$name.sl $*
if ($status != 0) then
	echo Could not create shared library: lib$name.sl
	exit -1
endif
exit 0
