#!/bin/sh

# RS/6000 AIX3
# script to produce listing of modules and function names in form
#               raster/lib/xwdio.o: xwdio::WriteRow
#
#       an argument is used as the directory from which to begin the search
#       otherwise the search begins from ./

find . -name "*.o" -exec /bin/nm -Oe '{}' \; | awk -F '|' '/Symbols/ {split($1, fl, " ");}; $2 !~ /^[._]/  && $3 > 0  && $4=="extern" {split ($2, fc, " "); print (fl[3], fc[1])}' | uniq
