#!/bin/sh
## ###################################################################### ##
##         Copyright IBM Corporation 1988,1991 - All Rights Reserved      ##
##        For full copyright information see:'andrew/doc/COPYRITE'        ##
## ###################################################################### ##

################################################
if [ $# -lt 2 -o $# -gt 3 ]; then
	echo 'usage: depends ${DEPEND} ${INCLUDES} [${DEFINES}]'
	exit 1
fi
################################################
DEPEND="$1"
INCLUDES="$2"
DEFINES="${3}"

################################################
any=
for x in *.[cC]; do
  case "$x" in
     '*.[cC]')
	echo "No Dependencies to Check...continuing...."
	exit 0 ;;
  esac
  break
done
################################################
C_DEPENDS=/tmp/Dep2_$$
DEPENDS=.depends
trap "rm -f $C_DEPENDS ${C_DEPENDS}.bak" 0
################################################
mv Makefile Makefile.BAK
sed -n -e '1,/##### DEPENDENCY LINE - DO NOT DELETE #####/p' Makefile.BAK > Makefile
################################################
>${C_DEPENDS}
${DEPEND} -s "##### DEPENDENCY LINE - DO NOT DELETE #####" -- ${DEFINES} -- ${INCLUDES} -f ${C_DEPENDS} *.[cC]

sed -e 's/##### DEPENDENCY LINE - DO NOT DELETE #####//g' ${C_DEPENDS} >> Makefile
