#!/bin/sh
# limitations:  assumes that this library will contain only the
# references and definitions included in the specified .o files.
# the libraries specified are only used by genstatl to generate
# an appropriate link line. (ATK libraries may be omitted.)
nm="$1"
libname="$2"
basedir="$3"
objs=($4)
libs=($5)
if ! echo $libs>$libname.lt; then
	echo "genrefs: Couldn't store library dependency list."
	exit 1
fi
exec $nm $objs |awk -f $basedir/etc/gen.awk>$libname.rf
