#!/bin/sh
set -o noglob
archive=yes
shared=no
result=0
expprog=
if [ "x$1" = "x-as" ]; then
	shift
	shared=yes
elif [ "x$1" = "x-s" ]; then
	shift
	archive=no
	shared=yes
fi

if [ "x$1" = "x-d" ]; then
	expprog="$2"
	shift 2
fi

name="$1"
basedir="$2"
linkprefix="$3"
shift 3
if [ $archive = yes ]; then
	echo "making archive lib"$name.a	
	rm -f lib$name.a
	list=  #list=()
	for ename in "$@"; do
	      if [ "${ename##*.}" == "o" ]; then 
   	             list="$ename $list" #list=("$ename" "${list[@]}") 
  	      fi
	done
	#if ! ar clq lib$name.a "${list[@]}"; then
	if ! ar clq lib$name.a $list; then
		echo "Couldn't create archive library for $name."
		result=1
	fi
	if ! ranlib lib$name.a; then
		echo "Couldn't ranlib archive library for $name."
		result=1
	fi
fi
if [ $shared = yes ]; then
	if [ ! -x $basedir/etc/mkatkshlib ]; then
		echo "Couldn't find $basedir/etc/mkatkshlib or it wasn't executable."
		echo "Perhaps ATK or the OS doesn't support shared libraries on this system?"
		exit 1
	fi
	if ! $basedir/etc/mkatkshlib $name $basedir "$linkprefix" "$@"; then
		echo "Couldn't create shared library for $name."
		result=$((result + 2))
	fi
fi
if [ -n "$expprog" ]; then
	if ! $expprog $name $basedir "$linkprefix" "$@"; then
		echo "$expprog failed for $name."
		result=$((result + 4))
	fi
fi
exit $result
