#!/bin/sh
# Copyright 1994 Carnegie Mellon University All rights reserved.
#  $Disclaimer: 
# Permission to use, copy, modify, and distribute this software and its 
# documentation for any purpose and without fee is hereby granted, provided 
# that the above copyright notice appear in all copies and that both that 
# copyright notice and this permission notice appear in supporting 
# documentation, and that the name of IBM not be used in advertising or 
# publicity pertaining to distribution of the software without specific, 
# written prior permission. 
#                         
# THE COPYRIGHT HOLDERS DISCLAIM ALL WARRANTIES WITH REGARD 
# TO THIS SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF 
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL ANY COPYRIGHT 
# HOLDER BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL 
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, 
# DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE 
# OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION 
# WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
# 
#  $
# Output a file defining a main function which registers each
# of the named classes.
# usage: mkdynmain class1 class2 etc....

echo "#include <andrewos.h>"
echo "#include <ATK.H>"

if [ "x$1" = "x-ctor" ]; then
	shift
	if [ "x$1" = "x-main" ]; then	
		shift
		echo "int main() { return 0; }"
	fi
	for name; do
		echo "extern ATKregistryEntry ${name}_ATKregistry_;"
	done
	echo "namespace {"
	echo "class ATKRegisterClass { public:"
	echo "inline ATKRegisterClass(ATKregistryEntry *reg) {"
	echo "	ATK::RegisterClass(reg); }"
	echo "inline ~ATKRegisterClass() { }"
	echo "};"
	for name; do
		echo "static ATKRegisterClass ${name}$$_(&::${name}_ATKregistry_);"
	done
	echo "}"
else
if [ "x$1" = "x-" ]; then
	shift
	main=$1
	shift
else
	main=main
fi

for name; do
echo "extern ATKregistryEntry ${name}_ATKregistry_;"
done

echo 'extern "C" '"int $main(int argc, char **argv) {"
for name; do
echo "ATKregister($name);"
done

echo "return 0;"
echo "}"
fi
