#!/bin/sh
# Copyright 1994 Carnegie Mellon University All rights reserved.
#
# Output a file defining a main function which registers each
# of the named classes.
# usage: mkdynmain class1 class2 etc....

echo "#include <andrewos.h>"
echo "#include <ATK.H>"

if [ "x$1" = "x-ctor" ]; then
	shift
	if [ "x$1" = "x-main" ]; then	
		shift
		echo "int main() { return 0; }"
	fi
	for name; do
		echo "extern ATKregistryEntry ${name}_ATKregistry_;"
	done
	echo "namespace {"
	echo "class ATKRegisterClass { public:"
	echo "inline ATKRegisterClass(ATKregistryEntry *reg) {"
	echo "	ATK::RegisterClass(reg); }"
	echo "inline ~ATKRegisterClass() { }"
	echo "};"
	for name; do
		echo "static ATKRegisterClass ${name}$$_(&::${name}_ATKregistry_);"
	done
	echo "}"
else
if [ "x$1" = "x-" ]; then
	shift
	main=$1
	shift
else
	main=main
fi

for name; do
echo "extern ATKregistryEntry ${name}_ATKregistry_;"
done

echo 'extern "C" '"int $main(int argc, char **argv) {"
for name; do
echo "ATKregister($name);"
done

echo "return 0;"
echo "}"
fi
