/* gtest.c
	test the gentext object
 
	Copyright 1996 Carnegie Mellon University All rights reserved.
	$Disclaimer: 
 * Permission to use, copy, modify, and distribute this software and its 
 * documentation for any purpose and without fee is hereby granted, provided 
 * that the above copyright notice appear in all copies and that both that 
 * copyright notice and this permission notice appear in supporting 
 * documentation, and that the name of IBM not be used in advertising or 
 * publicity pertaining to distribution of the software without specific, 
 * written prior permission. 
 *                         
 * THE COPYRIGHT HOLDERS DISCLAIM ALL WARRANTIES WITH REGARD 
 * TO THIS SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF 
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL ANY COPYRIGHT 
 * HOLDER BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL 
 * DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, 
 * DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE 
 * OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION 
 * WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 * 
 *  $
 */

#include <andrewos.h>
#include <gentext.H>

extern void doStaticLoads();

void main(register int	   argc, register char   **argv);
void printdata(register class gentext  *dobj);

	void 
main(register int	   argc, register char   **argv)  {
	register class gentext *dobj;
	boolean debug = TRUE;

	FILE *f;
	char *fnm;
	short i;
    
	printf("Start\n"); fflush(stdout);

/*	Cause static linking and loading of most ATK routines:
 */
	doStaticLoads(); /* found in statl.C generated by genstatl, 
				see help genstatl. */

/* dynamically load gentext so gtest need not be relinked when gentext is recompiled */

	fnm = NULL;
	for (i = 1; i < argc; i++) {
		if (argv[i][0] == '-')
			switch (argv[i][1]) {
				case 'f': /* Debugging. */
					debug = FALSE;
					break;
				default: /* Unknown switch. Treat it as a file... */
					fnm = argv[i]+1;
					break;
			}
		else { /* It's a file right? */
			fnm = argv[i];
		}
	}

	printf("About to create a gentext\n"); fflush(stdout);

	if (fnm && (f=fopen(fnm, "r")))
		dobj = gentext::CreateFromNamedFile(fnm);
	else 
		dobj = gentext::Create(
			"Does <|!marker expr|>it work: <|expr|>\n");

	if (dobj == NULL) {
		printf("NULL returned from creation\n");
		exit(2);
	}

	printdata(dobj);

	dobj->SetVar( "expr", "YES!");
	printf("var is set\n");  fflush(stdout);
	dobj->Instantiate( "");
	printf("text is instantiated\n");   fflush(stdout);
 	dobj->WriteVarToFile( "gentextq000", "/tmp/gout");
}

	void 
printdata(register class gentext  *dobj)  {
	FILE *f = fopen("/tmp/gnout", "w");
	printf("gentext data object at 0x%lx\n", dobj);
	fflush(stdout);
 	dobj->Write( f, 91, 0);
	fclose(f);
}

