#!/bin/sh
#
# Based on printscribe which is a Copyright IBM utility.
# For full copyright information see 'andrew/config/COPYRITE'

# discover if we should act like a filter, or emit
# files.  Output filenames are the input filename with .PS appended
# GROSSNESS: We need to assemble a list of args to pass through to 
# ezprint.  This means we need to know what they all are, so we can
# preserve more than just flags.  (like -o filename).
# So if new args come along that we want to forward to ezprint, we
# have to add them here.
# We also delete certain args like -S which don't make any sense.
#
# Any args we don't understand are passed thru as booleans.
# Any arg not begining with a dash that isn't parsed out of a command
# arg is assumed to be a file.
# If we go through all the args and never print a file, we assume we're a
# pipe.
#
# For my next trick, I will invent infinite improbability drive -wdc.

PASSTHRU=""

roff=troff
t=psc
post=psdit
type ditroff >/dev/null && roff=ditroff
# assume troff == groff if groff present
type groff >/dev/null && t=ps post=grops

while [ $# -gt 0 ]; do
    case "$1" in
        -e|-c|-C|-N|-T|-n|-o|-O|-a|-m|-l|-v)
            PASSTHRU="$PASSTHRU $1"
            shift
            if [ $# = 0 ]; then
                echo ez2ps: Missing argument -- try again.
                exit 1
            fi
            PASSTHRU="$PASSTHRU $1"
            ;;
        -S)
            shift
            if [ $# = 0 ]; then
                echo ez2ps: Missing argument -- try again.
                exit 1
            fi
            ;;
        -S*|-s*)
            ;;
        -q*|-i*|-I*|-E*|-C*|-p*|-t*|-h*|-n*|-V*|-z*|-FE*|-Fe*|-*)
            PASSTHRU="$PASSTHRU $1"
            ;;
        default:
            if [ $# -gt 2 ]; then
                echo ez2ps: Last two args should be files.
                exit 1
            elif [ $# = 2 ]; then
                exec ezprint -q -t $PASSTHRU $1 | eqn  | $roff -T$t | $post > ${2}
                exit 0
            elif [ $# = 1 ]; then
                exec ezprint -q -t $PASSTHRU $1 | eqn  | $roff -T$t | $post
                exit 0
            fi
    esac
    shift
done

exec ezprint -q -s -t  $PASSTHRU | eqn  | $roff -T$t | $post
