#! /bin/sh
auisdir=${0%/*/*}
dir=${1:-$auisdir}
filt=cat
type c++filt >/dev/null 2>&1 && filt=c++filt
(
  find $dir -name "*.a" -exec nm -og '{}' \; | awk '/ T / {print ($0);}'
  find $dir -name "*.so" -exec nm -Dog '{}' \; | awk '/ T / {print ($0);}'
) | sed "s%${dir%/}/%%" | $filt
