#!/bin/sh
name=$1
shift
basedir=$1
shift
linkprefix="$1"
shift
echo "making lib"$name.so
rm -f lib$name.so shr.o
echo "Creating shared object."
if ! $linkprefix gcc -Wl,--exclude-libs=ALL -shared -o lib$name.so "$@"; then
	echo Could not create shared library: lib$name.so
	exit 1
fi
exit 0
