#!/bin/sh
## ###################################################################### ##
##         Copyright IBM Corporation 1988,1991 - All Rights Reserved      ##
##        For full copyright information see:'andrew/doc/COPYRITE'     ##
## ###################################################################### ##
# $Disclaimer: 
# Permission to use, copy, modify, and distribute this software and its 
# documentation for any purpose and without fee is hereby granted, provided 
# that the above copyright notice appear in all copies and that both that 
# copyright notice and this permission notice appear in supporting 
# documentation, and that the name of IBM not be used in advertising or 
# publicity pertaining to distribution of the software without specific, 
# written prior permission. 
#                         
# THE COPYRIGHT HOLDERS DISCLAIM ALL WARRANTIES WITH REGARD 
# TO THIS SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF 
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL ANY COPYRIGHT 
# HOLDER BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL 
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, 
# DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE 
# OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION 
# WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
# 
#  $


BF=`basename $2 .n`
TBASE=/tmp/$BF.TMP
OUTF=/tmp/$BF.OUT
COMF=/tmp/$BF.EX
mv $2 $OUTF
cat $1 $OUTF > $2
echo $3 2\> $TBASE > $COMF
. $COMF
cat $TBASE $OUTF | awk '
{
if($1 == ".iy:" && $2 == "TEXTTAG" && NF == 4){ 
	page[$3] = $(NF)
	section[$3] = lastsection
}
else if($1 == ".iw:"){ lastsection = $2 }
else if($1== "XXX" &&  $2 == "\\\"TEXTREF"){
	if(NF == 3) {
		if(section[$3] == "") print "???"
		else print section[$3]
		}
	else if (NF == 4)  {
		if(page[$4] == "") print "???"
		else print page[$4]
		}
}
else print $0
}
' >  $2
rm $COMF $TBASE $OUTF
